# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-13 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import restaurents.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurents', '0005_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[restaurents.validators.validate_category]),
        ),
    ]
