# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-13 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190413_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
