# Generated by Django 2.1.5 on 2019-03-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kitchen',
        ),
    ]
