# Generated by Django 2.1.5 on 2019-04-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenorderbook',
            name='fname_of_orderer',
            field=models.CharField(default='', max_length=120),
        ),
    ]
