# Generated by Django 2.1.5 on 2019-04-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kitchenorderbook_fname_of_orderer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenorderbook',
            name='fname_of_orderer',
        ),
    ]
