# Generated by Django 2.1.5 on 2019-03-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_kitchenorderbook_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenorderbook',
            name='updated1',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
