# Generated by Django 2.1.5 on 2019-03-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_kitchenorderbook_updated1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenorderbook',
            name='updated1',
        ),
    ]
