# Generated by Django 2.1.5 on 2019-03-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_remove_kitchenorderbook_updated1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenorderbook',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
