# Generated by Django 2.1.5 on 2019-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_auto_20190326_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenorderbook',
            name='order_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
